{{- if .Values.proxyPatches.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-patches
  labels:
    app: proxy-patches
    component: proxy-patches
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: proxy-patches
      component: proxy-patches
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/proxy-patches/configmap.yaml") . | sha256sum }}
      labels:
        app: proxy-patches
        component: proxy-patches
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        hub.jupyter.org/network-access-proxy-api: "true"
    spec:
      nodeSelector: {{ toJson .Values.proxyPatches.nodeSelector }}
      volumes:
        - name: nginx-config
          configMap:
            name: proxy-patches-nginx-config
        - name: nginx-files
          configMap:
            name: proxy-html-files
        - name: proxy-help-config
          configMap:
            name: proxy-help-config

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- . | toYaml | nindent 8 }}
      {{- end }}

      containers:
      - name: nginx
        image: nginx:1.13.6
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: nginx-config
          - mountPath: /srv/proxy-patches/
            name: nginx-files
      - name: proxy-help
        image: {{ .Values.proxyPatches.image }}
        volumeMounts:
          - mountPath: /etc/proxy
            name: proxy-help-config
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: CHECK_PROXY_INTERVAL
            value: {{ .Values.proxyPatches.interval | quote }}
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub
                key: hub.config.ConfigurableHTTPProxy.auth_token
{{- end }}
